### ISSUE TITLE
IMU Gravity Vector Test

### ISSUE THREAD

**Issue by xlDownxl** [PyojinKim/MWMS#1]
Hello everyone,

first of all, thank you for the great work and the great repository!
After I ran the ICL dataset successfully, I asked myself if you also included some code to test your method with the IMU gravity vector instead of RGBD. I personally did not find any code on the IMU part in the repository, did I oversee it or is there no demo code for that part of the method provided?

Thank you already for your help!

**Comment by PyojinKim** [comment]
Hi xlDownxl,

You are right! There is no demo code for the IMU gravity vector case.
But it is super easy to extend from the RGB-D case to the IMU gravity vector case.
All you have to do is just to update the variable "planeNormalVector" not from RGBD, but from IMU gravity vector data.

FYI, you can easily obtain the gravity direction vector using iOS or Android API.
https://developer.apple.com/documentation/coremotion/getting_processed_device-motion_data

Thanks,
Pyojin Kim.

**Comment by xlDownxl** [comment]
Hey Pyojin,

Thank for you quick reply!
I recorded a dataset containing of RGBD images as well as Gravity Vectors with an iPhone as detailed in the link you posted.
Then, I replaced the variable "planeNormalVector" with the gravity vector as you suggested. 
The issue I am facing now is that after some frames are processed successfully, the script crashes because it can not find the corresponding vanishing points between the previous and current frame. I observed the value of  R_cM_new changing from:
   -0.9944    0.0989    0.0380
    0.0723    0.3715    0.9256
    0.0774    0.9232   -0.3765
to:
   -0.3495    0.9361    0.0398
    0.3634    0.0963    0.9266
    0.8636    0.3384   -0.3739
within one frame. The last column shows the gravity vector which, as one can see, did not change much (the camera movement is very small).

I already tried a few things, but I have not been able to fix this problem myself. I forked your repository here and added my gravity vector dataset to it: https://github.com/xlDownxl/MWMS.
It would mean a lot to me if you could take a quick look at it and suggest some future steps for me.

Again, thanks for the great work and code!
Best Regards
Niclas
