### ISSUE TITLE
optsLAPO lacks parameters

### ISSUE THREAD

**Issue by skcksjhcnsk** [PyojinKim/MWMS#2]
Hello
First of all，thanks for your great work.I have some questions to ask you. When I was running the code, there was an error, which prompted me that optsLPVO lacks parameters. There should be 23 parameters, but there are only 20 parameters in the load_param_MWMS.m file,As shown in the picture below.I would appreciate it if you could help me.Thanks for your work again!
![image](https://user-images.githubusercontent.com/89959593/220012781-da10148f-21d5-46ff-ba62-bddc3c72179d.png)

**Comment by PyojinKim** [comment]
Hi skcksjhcnsk,

I recommend using the function "estimateSurfaceNormalGradient.m" instead of mexw64.
It seems like I added some another configuration parameters when I made mexw64.
You can easily make your own mex file with "estimateSurfaceNormalGradient.m".

Thanks,
Pyojin Kim.

**Comment by skcksjhcnsk** [comment]
Hello,
Thanks for your help，i've fixed that problem!
Thanks again.
